TheEasyFood/TheEasyFood/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('products/', include('products.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

TheEasyFood/accounts/urls.py
from django.urls import path
from django.urls.conf import include
from .import views

urlpatterns = [
    path('',views.loginPage,name='loginPage'),
    path('registration',views.registration,name='registration'),
    path('logoutUser',views.logoutUser,name='logoutUser'),
]

TheEasyFood/products/urls.py
from django.urls import path
from django.urls.conf import include
from .import views

urlpatterns = [
    path('homePage',views.homePage,name='homePage'),
    path('productDetails/<int:pk>/',views.productDetails, name='productDetails'),
    path('search',views.search,name='search'),
    path('checkout',views.checkout,name='checkout'),
    path('myOrders',views.myOrders,name='myOrders'), 
    path('myProfile/<int:pk>/',views.myProfile, name='myProfile'),
    path('about',views.about,name='about'), 
]

TheEasyFood/products/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models.fields import DateField

# Create your models here.
class category (models.Model):
    category = models.CharField(max_length=20, unique=True)
    
    def __str__(self) -> str:
        return self.category

class product(models.Model):
    product_name= models.CharField(max_length=50, blank=False)
    product_description=models.CharField(max_length=500,null=False, blank=False)
    cover_photo=models.ImageField(null=False, blank=False)
    product_category = models.ForeignKey(category, null=True, on_delete= models.SET_NULL)
    product_price = models.PositiveIntegerField(null=False, blank=False)
    product_piece = models.PositiveIntegerField(null=False, blank=False)

    def __str__(self) -> str:
        return 'Product: '+self.product_name 

    def get_absolute_url(self):
        return reverse('productDetails', kwargs={'pk':self.id})

class images(models.Model):
    product=models.ForeignKey(product,on_delete=models.CASCADE)
    image=models.ImageField(blank=False, null=False)

    def __str__(self):
        return self.product.product_name

class review (models.Model):
    product=models.ForeignKey(product,on_delete=models.CASCADE)
    review=models.TextField(max_length=1000)
    user=models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    time=models.DateTimeField(auto_now_add=True,null=True)

class status(models.Model):
    status = models.CharField(max_length=50,default='Order Receieved')

    def __str__(self):
        return self.status

class order(models.Model):
    customer=models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    order_id= models.AutoField(primary_key=True)
    items_json= models.CharField(max_length=5000)
    address=models.CharField(max_length=500)
    phone = models.CharField(max_length=15, default="")
    status=models.ForeignKey(status,on_delete=models.SET_NULL,null=True)
    order_time=models.DateTimeField(auto_now_add=True,null=True)
    update_time=models.DateTimeField(auto_now=True,null=True)

TheEasyFood/products/forms.py
from django import forms
from .models import review

class reviewForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea(attrs={'rows':2, 'cols':30}))

    class Meta:
        model= review
        fields = ['review']
        

TheEasyFood/products/views.py
from django.shortcuts import redirect, render, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from accounts.models import profile
from accounts.forms import userRegistration,profileRegistration
from .models import product,images,review,order
from .forms import reviewForm
import datetime

# Create your views here.
@login_required(login_url='loginPage')
def homePage(request):
    products = product.objects.all().order_by('-id') #Latest products will be shown at 1st
    context = {'products':products}
    return render (request, 'homepage.html',context)

@login_required(login_url='loginPage')
def productDetails(request,pk):
    product_details = product.objects.get(id=pk)  #Contains information of a particular product
    product_images = images.objects.filter(product=product.objects.get(id=pk)) #Contains information of a particular product's images
    new_review = reviewForm()
    reviews = review.objects.filter(product=product.objects.get(id=pk)).order_by('-id')

    if request.method == 'POST':
        new_review = reviewForm(request.POST)
        if new_review.is_valid():
            new_review = new_review.save(commit=False)
            new_review.product = product_details
            new_review.user = request.user
            new_review.time = datetime.datetime.now()
            new_review.save()
            return HttpResponseRedirect(product_details.get_absolute_url())

    context = {'product_details':product_details,
    'product_images':product_images,
    'new_review':new_review,
    'reviews':reviews
    }
    return render (request,'product_details.html',context)

@login_required(login_url='loginPage')
def search(request):
    query = request.GET.get('query')
    if query:
        products = product.objects.filter(product_name__icontains=query)
        context = {'products':products}
        return render(request,'search.html',context)
    else:
        return redirect('homePage')

@login_required(login_url='loginPage')
def checkout(request):
    if request.method=="POST":
        items_json = request.POST.get('itemsJson', '')        
        address = request.POST.get('address', '')        
        phone = request.POST.get('phone', '')
        newOrder = order(items_json=items_json, customer=request.user, address=address,phone=phone)
        newOrder.save()        
        id = order.order_id
        messages.info (request, 'Your Order is accepted !!!')               
        return render (request,'checkout.html',{'id': id})
    return render (request,'checkout.html')

@login_required(login_url='loginPage')
def myOrders(request):
    orders = order.objects.all().order_by('-order_id') 
    context = {'orders':orders}
    print(orders[0].items_json)
    

    return render(request,'myorders.html',context)

@login_required(login_url='loginPage')
def myProfile(request,pk):
    previousInfo = profile.objects.get(id=pk)
    editUser = userRegistration(instance=request.user)
    editProfile = profileRegistration(instance=previousInfo)

    if request.method == 'POST':
        editUser = userRegistration(request.POST,instance=request.user)
        editProfile = profileRegistration(request.POST,request.FILES,instance=previousInfo)
        if editUser.is_valid() and editProfile.is_valid():
            editUser.save()
            editProfile.save()
            messages.success(request,'Account information is edited. Please login again..')
            return redirect('/')
    
    else:
        context = {'previousInfo':previousInfo,
        'editUser':editUser,
        'editProfile':editProfile}
        return render (request, 'myprofile.html',context)   


@login_required(login_url='loginPage')
def about(request):
    return render(request,'about.html')

TheEasyFood/products/templates/about.html
{% extends 'base_homepage.html' %}
{% load static %}

{% block content %}

<div class="container" id="about">
    <h1>Welcome to My Auction</h1>
    <ul>The Project is done by:
        <li>Rezwanul Haque Tonmoy</li>
        <li>Jubair Dihan</li>
        <li>Shakil Ahmed</li>
        <li>Afsin Orni</li>
        <li>Sabiha Mim</li>
    </ul>
</div>
{% endblock %}

TheEasyFood/products/templates/base_homepage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/productDetails.css' %}">
    <link rel="stylesheet" href="{% static 'css/myorders.css' %}">
    <link rel="stylesheet" href="{% static 'css/myprofile.css' %}">
    <link rel="stylesheet" href="{% static 'css/about.css' %}">
    <style>
        body {
            background-color: rgb(219, 226, 226);
        }
    </style> <!-- single css for changing body color of every page-->
    <title>The Easy Food</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'homePage' %}">
            <img src="/static/images/food_logo.jpg" width="30" height="30" class="d-inline-block align-top" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'homePage' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <!-- <li class="nav-item">
                    <a class="nav-link" href="#">My Cart(<span id="cart">0</span>) </a>
                </li>                 -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myOrders' %}">My Orders </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'about' %}">About Us</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{request.user}}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'myProfile' request.user.profile.pk %}">Your Profile</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'logoutUser' %}">Log out</a>

                    </div>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'search' %}">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="query">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
            <!-- <button type="button" class="btn btn-secondary mx-2" data-toggle="tooltip" data-placement="bottom"
                title="Tooltip on bottom">
                My Cart(<span id="cart">0</span>)
            </button> -->
            <button type="button" class="btn btn-secondary mx-2" id="popcart" data-container="body" data-toggle="popover"
                data-placement="bottom" data-html="true" data-content="Vivamus
sagittis lacus vel augue laoreet rutrum faucibus.">
                My Cart(<span id="cart">0</span>)
            </button>
        </div>
    </nav>
    {% block content%}


    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
    </script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
    </script>
    <script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/checkout.js' %}"></script>
</body>

</html>

TheEasyFood/products/templates/checkout.html
{% extends 'base_homepage.html' %}
{% load static %}

{% block content %}



<div class="container">
    <div class="col my-4">
        <h1>Step 1 - Easy Food - Review Your Cart Items</h1>
        {% for message in messages %}
        <p>{{message}}</p>
        {% endfor %}
        <div class="mt-4">
            <ul class="list-group" id="items">

            </ul>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item active" aria-current="page">Your Cart Total is <b><span id="totalPrice"></span></b> TK. Thanks for using Easy Food. Enter your details below to place order</li>
                </ol>
              </nav>
            
        </div>
    </div>
    <div class="col my-4">
        <h1>Step 2 - Enter Address and Phone number to Confirm</h1>
        <form method="POST" action="{% url 'checkout' %}">
            {% csrf_token %}
            <input type="hidden" name="itemsJson" id="itemsJson">
            <div class="form-group">
                <label for="inputAddress">Address</label>
                <input type="text" class="form-control" id="address" name="address"
                    placeholder="Enter Your Address Please">
            </div>
            <div class="form-group">
                <label for="inputPhone">Phone Number</label>
                <input type="tel" class="form-control" id="phone" name="phone"
                    placeholder="Enter Your Phone Number Please">
            </div>
            <button type="submit" class="btn btn-primary" id="placeOrder">Place Order</button>
        </form>
    </div>
</div>
{% endblock %}

TheEasyFood/products/templates/homepage.html
{% extends 'base_homepage.html' %}
{% load static %}

{% block content %}

<div class="container">
    <div class="row">
        {% for product in products %}
        <div class="col-lg-4 mb-4">
            <div class="card">
                <img class="card-img-top" src="{{product.cover_photo.url}}" alt="">

                <div class="card-body">
                    <h5 class="card-title" id="namepr{{product.id}}">{{product.product_name}}</h5>
                    <p class="card-text" >                        
                        Price: <span id="pricepr{{product.id}}"> {{product.product_price}}</span>Tk<br>
                    </p>

                    <a href="{% url 'productDetails' product.pk %}" class="btn btn-primary btn-sm">
                        Product Details
                    </a>
                    <span id="divpr{{product.id}}" class="divpr">
                        <button id="pr{{product.id}}" class="btn btn-primary cart">Add To Cart</button>
                    </span>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

TheEasyFood/products/templates/myorders.html
{% extends 'base_homepage.html' %}
{% load static %}

{% block content %}
<div class="container">
    <table class="table" id="table">
        <thead>
          <tr>
            <th scope="col">Order ID</th>
            <th scope="col">Order Time</th>
            <th scope="col">Order Status</th>            
          </tr>
        </thead>
        <tbody>
          {% for order in orders %}
          {% if order.customer == user %}
          <tr>
            <th scope="row">{{order.order_id}}</th>
            <td>{{order.order_time}}</td>
            <td>{{order.status}}<br>{{order.update_time}}</td>            
            
          </tr>
          
          {% endif %}  
      {% endfor%}
        </tbody>
      </table>
</div>


{% endblock %}

TheEasyFood/products/templates/myprofile.html
{% extends 'base_homepage.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container" id="profile">
            <div class="row">
                <div class="col-lg-5" id="profile_info">
                    <h3>Current Profile Information </h3>
                    <p>User Name: {{ previousInfo.user.username }}<br> 
                        User Email: {{ previousInfo.user.email }}
                         </p>
                         <img src="{{previousInfo.profile_picture.url}}" class="rounded float-left" alt="..." width="70%" height="auto">                    
                </div>
                <div class="col-lg-7" id="profile_form">
                    <h3>Edit your profile </h3>
                    <form action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ editUser | crispy }}
                        {{ editProfile | crispy }}
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                    </div>
                </div>
            
</div>

{% endblock %}

TheEasyFood/products/templates/product_details.html
{% extends 'base_homepage.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container" id="product">
    <div class="row">
        <!-- {% for image in product_images %}
                  {% endfor%} -->
        <div class="col-lg-8" id="product_images">
            <h3>Product images</h3>
            <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img class="d-block w-100" src="{{ product_details.cover_photo.url }}" alt="First slide">
                    </div>
                    {% for image in product_images %}
                    <div class="carousel-item">
                        <img class="d-block w-100" src="{{ image.image.url }}" alt="Second slide">
                    </div>
                    {% endfor%}
                </div>
                <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
            
        </div>
        <div class="col-lg-4" id="product_info">
            <h3>Product Information </h3>
            <p>
                <b>Category: </b>{{ product_details.product_category }}<br><br>
                <b>Name: </b>{{product_details.product_name}}<br><br>
                <b>Piece(s): </b>{{ product_details.product_piece }}<br><br>
                <b>Price: </b>{{ product_details.product_price }} TK<br><br>
                <b>Description: </b>{{product_details.product_description}}<br><br>
                
            </p>
        </div>
    </div>

        <form action="" , method="POST">
            {%csrf_token%}
            <h3>Please leave a review </h3>
            <div class=""> <textarea name="review" cols="30" rows="2" class="textarea form-control" required=""
                    id="id_review"></textarea> </div>
            <button type="submit" id="review_button" class="btn btn-primary">Submit</button>
        </form>
        <blockquote class="my-5 cmmnt_1526">
            {% for review in reviews %}
            <footer>
                <p>{{ review.review |safe }}</p>
                <p> Reviewed by: {{ review.user|capfirst }}</p>
                <p>- {{ review.time.date |safe }}</p>
                <hr class="my-4">
            </footer>
            {% endfor %}
        </blockquote>
</div>



{% endblock %}

TheEasyFood/products/templates/search.html
{% extends 'base_homepage.html' %}
{% load static %}

{% block content %}

<div class="container">
    <div class="row">
        {% for product in products %}
        <div class="col-lg-4 mb-4">
            <div class="card">
                <img class="card-img-top" src="{{product.cover_photo.url}}" alt="">

                <div class="card-body">
                    <h5 class="card-title" id="namepr{{product.id}}">{{product.product_name}}</h5>
                    <p class="card-text" >                        
                        Price: <span id="pricepr{{product.id}}"> {{product.product_price}}</span>Tk<br>
                    </p>

                    <a href="{% url 'productDetails' product.pk %}" class="btn btn-outline-primary btn-sm">
                        Product Details
                    </a>
                    <span id="divpr{{product.id}}" class="divpr">
                        <button id="pr{{product.id}}" class="btn btn-primary cart">Add To Cart</button>
                    </span>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}